name: plasmid workflow
on: push
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nf-core/setup-nextflow@v1
      - uses: eWaterCycle/setup-singularity@v7
      - run: nextflow run main.nf -profile test,singularity --outdir output/
